### PR TITLE
Added support for p12 and IO object certificates.

### PR DESCRIPTION
**Pull request by benubois**
Hi @ostinelli,

Thanks for the great library! Currently, in production my certificates are saved as p12 files, which can be converted to pem in ruby so it would be useful for me to not change the format ahead of time.

With these additions it is possible to use a PKCS 12 (.p12) formatted certificate, or any Ruby object that responds to :read, such as StringIO to allow users to provide a certificate however it is most convenient for them.

Thanks!

### CODE REVIEW

**Comment by benubois** [comment]
😕 Hmm, not sure why Travis is reporting an error. The tests seem to run fine locally. Any thoughts?

**Comment by ostinelli** [comment]
@benubois, thank you for this addition!

One thing though: The HTTP2 client part of Apnotic 0.7.0 has raised some interest and I've been asked if I could extract it to a separate gem. So I did, and I've just released [NetHttp2](https://github.com/ostinelli/net-http2).

In the coming days I will release a version of Apnotic that relies upon this gem. Would you mind waiting for when I'm done with the refactoring and resubmit your pull request against the new code?

As far as the broken tests: I am not really sure why these broke, however it looks like you forgot to commit the `apn.p12` file referenced from here:
https://github.com/feedbin/apnotic/blob/p12/spec/support/api_helpers.rb#L10

**Comment by benubois** [comment]
@ostinelli 

Ah, good point! I'll keep an eye on the releases and resubmit (with apn.p12) then.

Thanks!

**Comment by ostinelli** [comment]
Thanks! I will also ping you, just in case :)

**Comment by ostinelli** [comment]
FYI, I've completed the refactoring early this morning! Let me know if you want to issue a PR or you don't have the time for it.

Thanks!

**Comment by ostinelli** [comment]
FYI: I've completed the said refactoring early this morning! Feel free to submit a new PR :)

**Comment by adamvduke** [comment]
I was considering adding support for `read`able objects too. Awesome to see it's already in the works.

**Comment by ostinelli** [comment]
Thank you @adamvduke :)

**Pull request closed without merging**
