### PR TITLE
Add token-based authentication.

### PR DESCRIPTION
**Pull request by benubois**
Hello,

Apple recently added support for authenticating via JSON Web Token instead of and SSL certificate. The key advantages are that the key never expires and can be used for multiple apps.
- [Provider Authentication Tokens docs](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH101-SW21)
- Provision [Apple Push Notification Authentication Key](https://developer.apple.com/account/ios/certificate/create)

I've made the updates to support JWTs, minus some tests.

However I was wondering if this is something you would be interested in having in Apnotic and if so could get some help before continuing?

When I run this with jwt it looks like the connection is closed immediately and no notifications are sent:

``` ruby
APNOTIC_POOL = Apnotic::ConnectionPool.new(
  {
    auth_method: :token,
    cert_path: ENV['APPLE_KEY'],
    team_id:   ENV['APPLE_TEAM_ID'],
    key_id:    ENV['APPLE_KEY_ID'],
  },
  size: 5
)
APNOTIC_POOL.with do |connection|
  notifications.each do |_, notification|
    push = connection.prepare_push(notification)
    push.on(:response) do |response|
      if response.status == '410' || (response.status == '400' && response.body['reason'] == 'BadDeviceToken')
        # handle failure
      end
    end
    connection.push_async(push)
  end
  connection.join
end
EOFError: end of file reached
    from /Users/ben/.rbenv/versions/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:178:in `sysread_nonblock'
    from /Users/ben/.rbenv/versions/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:178:in `read_nonblock'
    from /Users/ben/Sites/feedbin/vendor/bundle/gems/net-http2-0.13.3/lib/net-http2/client.rb:111:in `block in socket_loop'
    from /Users/ben/Sites/feedbin/vendor/bundle/gems/net-http2-0.13.3/lib/net-http2/client.rb:108:in `loop'
    from /Users/ben/Sites/feedbin/vendor/bundle/gems/net-http2-0.13.3/lib/net-http2/client.rb:108:in `socket_loop'
    from /Users/ben/Sites/feedbin/vendor/bundle/gems/net-http2-0.13.3/lib/net-http2/client.rb:93:in `block (2 levels) in ensure_open'
```

It could just be that the JWT part is not what Apple is expecting, but I'm able to sign and decode the JWT in the `spec/apnotic/provider_token_spec.rb`.

Any thoughts about what might be going wrong would be great.

Thanks!

### CODE REVIEW

**Comment by benubois** [comment]
According to the docs an invalid provider token should still get a response saying the provider token is invalid so maybe we can rule that out? 

> Note: Only providers tokens signed with ES256 algorithm are supported by APNs. Unsecured JWT or JWT signed with other algorithms will be rejected with a response indicating an Invalid Provider Token.

**Comment by ostinelli** [comment]
Hi Ben,
Thank you for bringing this up. The `EOFError` just means that the connection was closed, if you upgrade to Apnotic `1.0.1` you will now see a `SocketError`.

Apple does this even with invalid certificates, so for instance if you use the development certificate in production it will just abruptly close the connection down, without providing a response. Also, I've seen sometimes differences between real behavior and documentation, so I wouldn't be too surprised if they just shut down the connection without sending data.

**Comment by benubois** [comment]
Turns out this code does work, but only when using sync pushes. 

I think the reason my original test was failing was it was using async pushes. In this case there is a new requirement from APNs:

> When you connect to APNs without a provider certificate, only one stream is allowed on the connection until you send a push message with valid token.

So apnotic would need to hold off on using multiple streams until the first notification is sent over a new connection.

Any thoughts on how to achieve this?

**Comment by benubois** [comment]
It looks like APNs tells you how many MAX_CONCURRENT_STREAMS are allowed when establishing the connection. MAX_CONCURRENT_STREAMS starts at 1 and then I think gets increased after a successful push. So this setting might need to be exposed by net-http2/http2. 

Anyway I realized getting this to work for async pushes is trickier than I thought and am suspending work on this for now. 

```
$ h2i api.development.push.apple.com
Connecting to api.development.push.apple.com:443 ...
Connected to 17.172.238.203:443
Negotiated protocol "h2"
[FrameHeader SETTINGS len=24]
[HEADER_TABLE_SIZE = 4096]
[MAX_CONCURRENT_STREAMS = 1]
[MAX_FRAME_SIZE = 16384]
[MAX_HEADER_LIST_SIZE = 8000]
```

**Comment by ostinelli** [comment]
Hi @benubois, thank you for taking the time to do this investigation!

I tend to wait a little when new functionalities come up to wait for Apple to settle on their specifications.
This is precious anyways, let's keep an eye on it, I need to investigate a possible `MAX_CONCURRENT_STREAMS` solution in NetHttp2.

**Comment by idyll** [comment]
This issue is almost definitely "MAX_CONCURRENT_STREAMS".

It needs to start at one and then Apple sends down messages that prompt you to increase it.

If I get the chance I will take a look at the implementation and see if I can help.

**Comment by idyll** [comment]
@ostinelli and @benubois I think you should re-open this.

The http-2 library respects the max concurrent streams already and just prevents opening new ones by throwing an exception -- which is possibly the right thing to do.

If you background this with sidekiq, it will retry due to the exception. At which point apple should allow more streams. The only thing I am not sure of is if the http-2 lib will see the new MAX_CONCURRENT_STREAMS value come down and then adjust itself. @igrigorik can you confirm?

If that is the case it might be better to just trigger the exception then having to handle retry or queueing logic in this gem. 

So I think this PR is likely a good candidate for how to handle JWT/APNS.

**Comment by igrigorik** [comment]
> If you background this with sidekiq, it will retry due to the exception. At which point apple should allow more streams. The only thing I am not sure of is if the http-2 lib will see the new MAX_CONCURRENT_STREAMS value come down and then adjust itself. @igrigorik can you confirm?

Yep: https://github.com/igrigorik/http-2/blob/bf4b930c19934521bb0ffcfa19486ff7e415ed55/spec/connection_spec.rb#L68

**Comment by jeff-savin** [comment]
Very interested in using this gem with the JWT/APNS feature.  What's the status on this development?  Any help needed?  @ostinelli

**Comment by ostinelli** [comment]
@jeff-savin @benubois I'm currently not doing any work on this.

**Comment by hc2p** [comment]
@jeff-savin i just tried @benubois code and it works for both sync- and async-pushes. (have a look at [my fork](https://github.com/hc2p/apnotic/tree/token), i just cherry-picked the commit from this PR onto latest master).
I'm almost sure i'm missing something though.

**Comment by jeff-savin** [comment]
Thanks @hc2p.  We did the same thing and are using it in production.  Not sure if we did any minor tweaks or not, it was an associate that ended up using it.  Thanks for the note.

**Comment by hc2p** [comment]
good to know! @ostinelli what's missing in this PR before it can get merged?

**Comment by ostinelli** [comment]
I only see a single commit labeled WIP. Looking at it, I am unsure whether there are all the necessary testing. Also, there's a comment stating whether or not we should expose `MAX_CONCURRENT_STREAMS`.

If anyone has the time to finalize this I can go ahead and merge.

**Comment by AmberWilkie** [comment]
Hey guys, any movement on this? Working on a project with APNS - would love to use this gem with token authorization. I can (try to) help if anything else is needed.

**Comment by ostinelli** [comment]
Hello, see my previous comment.

**Comment by benubois** [comment]
@ostinelli, I've made the necessary changes for this to be viable.

This requires changes to `net-http2`. See ostinelli/net-http2#22.

The Gemfile is temporarily pointing to the updated `net-http2` to pass tests, but this would need to be changed for a release.

This should also fix #29, by introducing a blocking call that checks if there are any streams available before allocating a new one.

**Comment by ostinelli** [comment]
@benubois this is great. Thank you for your input. Will be reviewing and merging in ASAP.

**Comment by ostinelli** [comment]
This has now been released as `1.2.0`. Again, thank you for your great contribution.

**Comment by rromanchuk** [comment]
do need to do anything special with the .p8 from apple?  Getting `OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: nested asn1 error` when initializing the connection object. I triple checked to make sure it wasn't user error. Also generated new keys.  One thing i noticed, the p8 key download from apple had `\n `s in the middle of the key. Is that format specification or inproper white space?

**Comment by benubois** [comment]
Hi @rromanchuk,

I didn’t have to do anything to the p8 file.

Could you provide the backtrack for that exception?

**Comment by rromanchuk** [comment]
This is most likely a user error, or something wrong with ios developer center. I'll investigate a little more. 

```ruby
Apnotic::Connection.new(
    {
      auth_method: :token,
      cert_path: StringIO.new(File.read(Rails.root.join("push_keys", "AuthKey_MQNR5NK3ZF.p8"))),
      key_id: Rails.application.secrets.apn_token_key_id,
      team_id: Rails.application.secrets.apple_team_id
    })
```

```
OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: nested asn1 error
	from /Users/ryan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/apnotic-1.1.0/lib/apnotic/connection.rb:75:in `initialize'
	from /Users/ryan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/apnotic-1.1.0/lib/apnotic/connection.rb:75:in `new'
	from /Users/ryan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/apnotic-1.1.0/lib/apnotic/connection.rb:75:in `rescue in ssl_context'
	from /Users/ryan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/apnotic-1.1.0/lib/apnotic/connection.rb:70:in `ssl_context'
	from /Users/ryan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/apnotic-1.1.0/lib/apnotic/connection.rb:27:in `initialize'
	from (irb):1:in `new'
	from (irb):1
	from /Users/ryan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.9/lib/rails/commands/console.rb:110:in `start'
	from /Users/ryan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.9/lib/rails/commands/console.rb:9:in `start'
	from /Users/ryan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/ryan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/ryan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.9/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by rromanchuk** [comment]
I'm and idiot, wrong version of the gem 🐒

**Pull request merged**
