### PR TITLE
Added support for p12 and IO object certificates.

### PR DESCRIPTION
**Pull request by benubois**
Updated #1.

### CODE REVIEW

**Comment by ostinelli** [comment]
Great, thank you! Can you please squash all of your commit into a single one, then push to your branch so that this PR gets updated? Thanks! Will pull in tomorrow.

**Comment by benubois** [comment]
Hi @ostinelli,

I think that `Dir[]` in [spec_helper.rb#6](https://github.com/ostinelli/apnotic/blob/81006d6c8a3a66063cc41b2eb4637c9d0d82b947/spec/spec_helper.rb#L6) was causing the test failures. It looks like [`Dir.glob`](http://ruby-doc.org/core-2.2.0/Dir.html#method-c-glob) can order files arbitrarily, so on these test failures I'm thinking `dummy_server.rb` was being required before its dependency `api_helpers.rb`

To fix this I've explicitly required `api_helpers.rb` in `dummy_server.rb`.

Thanks!

**Comment by benubois** [comment]
> Can you please squash all of your commit into a single one, then push to your branch so that this PR gets updated?

Done!

**Comment by ostinelli** [comment]
Merged in, thank you for your contribution!

**Pull request merged**
