### PR TITLE
Add mdm notifications support

### PR DESCRIPTION
**Pull request by bankair**
Hi all,

This branch adds support for MDM notifications.

A MDM notification is a nude notification with only the following payload (replace the PushMagicValue string by the correct push magic value sent by the iOS device during the register process):

```json
{ "mdm": "PushMagicValue" }
```

(see https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/MobileDeviceManagementProtocolRef/3-MDM_Protocol/MDM_Protocol.html#//apple_ref/doc/uid/TP40017387-CH3-SW3 for more details)

For the sake of simplicity (and to avoid mixing up token and magic push), I choose to use two mandatory keywords parameter to build the notification:

```ruby
connection = Apnotic::Connection.new(cert_path: "apns_certificate.pem", cert_pass: "pass")
notification = Apnotic::MdmNotification.new(token: '0LIZNDLZI34023I', push_magic: '09908NINZD09898')
response = connection.push(notification)
```

Those notifications serve not other purpose than notifying the device that it's MDM server has pending commands waiting for him to check. The reste of the process (commands check in, and execution) is taken care of by the iOS device and the MDM server.

### CODE REVIEW

**Comment by bankair** [comment]
An additional note: We'll be using this in production in a few days at Appaloosa.io. I'll let you know how it's going ;)

**Comment by bankair** [comment]
Hey, @ostinelli,

What do you think of that update ? Would you like us to update the README as well in order to merge ?

**Comment by ostinelli** [comment]
Sorry for the late response. Will be reviewing soon.

**Comment by ostinelli** [comment]
Can you please squash these commit into a single one, will review when done, thanks.

**Comment by bankair** [comment]
@ostinelli : Yep, sure done. Let me know if you need anything else.

Thanks

**Comment by bankair** [comment]
@ostinelli : Sorry, I did not see your remark about the README in the first place. I added a section explaining briefly how it work.

Let me know if you need anything else ;)

**Comment by ostinelli** [comment]
Merged, thank you.

**Comment by bankair** [comment]
Yay ! Nice. BTW, our fork is working great for us in production.

**Comment by ostinelli** [comment]
Great. Well, you can start using the official one now ^^_

**Pull request merged**
