### PR TITLE
Use loop instead of tail recursion

### PR DESCRIPTION
**Pull request by eyalv**

### CODE REVIEW

**Comment by eyalv-oz** [comment]
We use this gem in a server without the TCO enabled.
This change helps avoiding stack-overflow. We encountered this during load test when the callback handling was a bit slow.

**Comment by eyalv** [comment]
We use this gem in a server without the TCO enabled.
This change helps avoiding stack-overflow. We encountered this during load test when the callback handling was a bit slow.

**Comment by ostinelli** [comment]
Do you happen to know when was `unless` introduced? I can't remember why I set a loop in the first place...

**Comment by eyalv** [comment]
Are you referring to the "until" I've added?
I think it was always in the language. But you can change this to while not if you want.

**Comment by ostinelli** [comment]
Merged, thank you.

**Pull request merged**
