### PR TITLE
add support for apns-collapse-id

### PR DESCRIPTION
**Pull request by benr75**
I'm working on iOS 10 notifications and needed to support apns-collapse-id in the header values so that the value of an existing push could be updated with another remote notification with the same apns-collapse-id.  Realize I should have created a ticket to discuss first, but anyhow work is done and tests are passing, hopefully acceptable.  Worked perfect for me.

### CODE REVIEW

**Comment by ostinelli** [comment]
Hello, thank you for your contribution. Can you please add the related README instructions, and squash everything into a single reviewable commit?

**Comment by benr75** [comment]
Updated README, only reference I could find from Apple was the WWDC Talk, also rebased to one commit.

**Comment by ostinelli** [comment]
Thank you for your contribution!

**Comment by ostinelli** [comment]
FYI I will be releasing this one as `0.10.1` later tonight.

**Pull request merged**
